# -*- coding: utf-8 -*-
"""row64-assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Giozlz/78bfb13788d31525685a5b27df435cc0/row64-assignment.ipynb

Visualization 1
"""

import matplotlib.colors as cl
import matplotlib.pyplot as plt
import pandas as pd
import row64
import seaborn as sns

def ScatterPlotBasic(inDf, inCol1, inCol2):
    col1 = inDf.columns[inCol1]
    col2 = inDf.columns[inCol2]
    sns.scatterplot(color="#1F87B4",data=inDf,x=col1,y=col2,s=25)

#IMPORT("C:\Users\giova\Downloads\Housing Data - Sheet1.csv")
dfIn=row64.get_dataframe("Dataframe3")
df=dfIn.copy(deep=True)
ScatterPlotBasic(df,0,17)

"""Visuzalization 2"""

import matplotlib.colors as cl
import matplotlib.pyplot as plt
import pandas as pd
import row64
import seaborn as sns

def ScatterPlotBasic(inDf, inCol1, inCol2):
    col1 = inDf.columns[inCol1]
    col2 = inDf.columns[inCol2]
    sns.scatterplot(color="#1F77B4",data=inDf,x=col1,y=col2,s=25)

#IMPORT("C:\Users\giova\Downloads\Housing Data - Sheet1.csv")
dfIn=row64.get_dataframe("Dataframe8")
df=dfIn.copy(deep=True)
ScatterPlotBasic(df,0,4)

"""Visualzation 3"""

import matplotlib.colors as cl
import matplotlib.pyplot as plt
import pandas as pd
import row64
import seaborn as sns

def ScatterPlotBasic(inDf, inCol1, inCol2):
    col1 = inDf.columns[inCol1]
    col2 = inDf.columns[inCol2]
    sns.scatterplot(color="#1F77B4",data=inDf,x=col1,y=col2,s=25)

#IMPORT("C:\Users\giova\Downloads\Housing Data - Sheet1.csv")
dfIn=row64.get_dataframe("Dataframe3")
df=dfIn.copy(deep=True)
ScatterPlotBasic(df,0,38)